{{- if .Values.telegram.botToken }}
apiVersion: v1
kind: Secret
metadata:
  name: digital-mine-telegram
  labels: {{- include "dm.labels" . | nindent 4 }}
type: Opaque
stringData:
  botToken: {{ .Values.telegram.botToken | quote }}
  chatId: {{ .Values.telegram.chatId | quote }}
{{- end }}
