apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    {{- include "dm.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  {{- with .Values.web.strategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels: {app.kubernetes.io/component: web}
  template:
    metadata:
      labels:
        {{- include "dm.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/web-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: digital-mine
      automountServiceAccountToken: false
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- range . }}
        - name: {{ . }}{{ end }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "dm.image" (dict "root" . "name" .Values.image.web) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - {name: http, containerPort: 8080}
          readinessProbe:
            httpGet: {path: /healthz, port: http}
          livenessProbe:
            httpGet: {path: /healthz, port: http}
            periodSeconds: 20
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
          volumeMounts:
            - {name: nginx-conf, mountPath: /etc/nginx/conf.d, readOnly: true}
      volumes:
        - name: nginx-conf
          configMap: {name: web-nginx}
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels: {{- include "dm.labels" . | nindent 4 }}
spec:
  selector: {app.kubernetes.io/component: web}
  ports:
    - {name: http, port: 80, targetPort: http}
{{- with .Values.web.pdb }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web
  labels: {{- include "dm.labels" $ | nindent 4 }}
spec:
  {{- toYaml . | nindent 2 }}
  selector:
    matchLabels: {app.kubernetes.io/component: web}
{{- end }}
