apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  low-memory.xml: |
    <clickhouse>
      <logger><level>warning</level><console>1</console></logger>
      <max_server_memory_usage>{{ int64 .Values.maxServerMemoryUsage }}</max_server_memory_usage>
      <mark_cache_size>67108864</mark_cache_size>
      <uncompressed_cache_size>0</uncompressed_cache_size>
      <index_mark_cache_size>0</index_mark_cache_size>
      <max_concurrent_queries>50</max_concurrent_queries>
      <background_pool_size>2</background_pool_size>
      <background_merges_mutations_concurrency_ratio>2</background_merges_mutations_concurrency_ratio>
      <background_schedule_pool_size>16</background_schedule_pool_size>
      <background_common_pool_size>2</background_common_pool_size>
      <background_move_pool_size>1</background_move_pool_size>
      <background_fetches_pool_size>1</background_fetches_pool_size>
      <background_buffer_flush_schedule_pool_size>1</background_buffer_flush_schedule_pool_size>
      <background_message_broker_schedule_pool_size>1</background_message_broker_schedule_pool_size>
      <background_distributed_schedule_pool_size>1</background_distributed_schedule_pool_size>
      <merge_tree>
        <number_of_free_entries_in_pool_to_execute_mutation>2</number_of_free_entries_in_pool_to_execute_mutation>
        <number_of_free_entries_in_pool_to_lower_max_size_of_merge>2</number_of_free_entries_in_pool_to_lower_max_size_of_merge>
        <number_of_free_entries_in_pool_to_execute_optimize_entire_partition>2</number_of_free_entries_in_pool_to_execute_optimize_entire_partition>
      </merge_tree>
      <query_log remove="1"/>
      <query_thread_log remove="1"/>
      <query_views_log remove="1"/>
      <part_log remove="1"/>
      <trace_log remove="1"/>
      <metric_log remove="1"/>
      <asynchronous_metric_log remove="1"/>
      <text_log remove="1"/>
      <session_log remove="1"/>
      <processors_profile_log remove="1"/>
      <opentelemetry_span_log remove="1"/>
      <latency_log remove="1"/>
      <error_log remove="1"/>
      <query_metric_log remove="1"/>
      <prometheus>
        <endpoint>/metrics</endpoint>
        <port>9363</port>
        <metrics>true</metrics>
        <events>true</events>
        <asynchronous_metrics>true</asynchronous_metrics>
      </prometheus>
    </clickhouse>
  low-threads.xml: |
    <clickhouse>
      <profiles>
        <default>
          <max_threads>2</max_threads>
          <max_memory_usage>400000000</max_memory_usage>
        </default>
      </profiles>
    </clickhouse>
