image:
  repository: clickhouse/clickhouse-server
  tag: 26.3.42.3-alpine
  pullPolicy: IfNotPresent
existingSecret: dm-secrets   # ключи CH_USER, CH_PASSWORD
database: mine
resources: {}
maxServerMemoryUsage: 700000000
storage: 3Gi
